---
# =================================================================================================
# Areas
# =================================================================================================
- name: area/github
  color: "000000"
- name: area/helm
  color: "844FBA"

# =================================================================================================
# Charts
# =================================================================================================
- name: chart/k8s-resource
  color: "123456"
