---
area/docker:
  - changed-files:
      - any-glob-to-any-file: ".dockerignore"
      - any-glob-to-any-file: "Dockerfile"
      - any-glob-to-any-file: ".devcontainer/devcontainer.json"

area/github:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"

area/renovate:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/renovate.yaml"
      - any-glob-to-any-file: ".github/configs/renovate/*.json5"
      - any-glob-to-any-file: ".github/configs/renovate.json5"

area/helm:
  - changed-files:
      - any-glob-to-any-file: "charts/**"
