---
{{- if .Values.items }}
  {{- if ne .Values.kind "List" }}
  {{- fail "Items are only supported for objects of kind 'List'" }}
  {{- end }}

  {{- if .Values.spec }}
  {{- fail "Spec and Items are mutually exclusive!" }}
  {{- end }}
{{- end }}

apiVersion: {{ .Values.apiVersion }}
kind: {{ .Values.kind }}

metadata:
{{ toYaml .Values.metadata | indent 2 }}

{{ if .Values.spec }}
spec:
{{ toYaml .Values.spec | indent 2 }}
{{ end }}

{{ if .Values.items }}
items:
{{ toYaml .Values.items | indent 2 }}
{{ end }}