---
# apiVersion -- (string) The API version of the Kubernetes resource you're creating.
apiVersion:

# This defines the type of resource, such as "Pod", "Service", "Deployment", etc.
kind:

# -- (object) metadata Metadata for the Kubernetes resource.
metadata:

# -- (object) The specification for the Kubernetes resource.
spec:
