---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Helm Push
permissions: { contents: read }

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run
        default: false
        required: false
        type: boolean
  push:
    paths: ["charts/**"]

jobs:
  discover-charts:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.set-charts.outputs.charts }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Find Helm Charts
        id: set-charts
        run: |
          CHARTS=$(find charts -type f -name "Chart.yaml" -print0 | xargs -0 dirname | xargs -0 -n1 basename | jq -R -s -c 'split("\n")[:-1]')
          echo "charts=${CHARTS}" >> "$GITHUB_OUTPUT"
          echo "Found charts: ${CHARTS}"

  helm-push:
    needs: discover-charts
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chart: ${{ fromJson(needs.discover-charts.outputs.charts) }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Changed Files
        id: changed-files
        uses: bjw-s-labs/action-changed-files@b1144fc772fca235a50902c7bb6cc431cc7d8e27 # v0.3.2
        with:
          patterns: "./charts/${{ matrix.chart }}/Chart.yaml" # Trigger on version change in Chart.yaml

      - name: Setup mise
        if: steps.changed-files.outputs.changed_files != '[]' || github.event_name == 'workflow_dispatch'
        uses: jdx/mise-action@7a111ead46986ccad89a74ad013ba2a7c08c9e67 # v2.2.1

      - name: Package Helm chart
        if: steps.changed-files.outputs.changed_files != '[]' || github.event_name == 'workflow_dispatch'
        working-directory: ./charts/${{ matrix.chart }}
        run: helm package .

      - name: Helm login to GHCR
        if: steps.changed-files.outputs.changed_files != '[]' || github.event_name == 'workflow_dispatch'
        run: |
          echo ${{ secrets.GHCR_RW_TOKEN }} | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Push Helm chart to GHCR
        if: |
          (steps.changed-files.outputs.changed_files != '[]' && github.ref_name == 'main')
          ||
          ( github.event_name == 'workflow_dispatch' && inputs.dry-run == false)
        working-directory: ./charts/${{ matrix.chart }}
        run: helm push "$(ls ./*.tgz)" oci://ghcr.io/${{ github.repository }}
