---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Helm Schema
permissions: { contents: write }

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run
        default: true
        required: false
        type: boolean
  push:
    paths:
      - "charts/**/values.yaml"

jobs:
  discover-charts:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.set-charts.outputs.charts }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Find Helm Charts
        id: set-charts
        run: |
          CHARTS=$(find charts -type f -name "Chart.yaml" -print0 | xargs -0 dirname | xargs -0 -n1 basename | jq -R -s -c 'split("\n")[:-1]')
          echo "charts=${CHARTS}" >> "$GITHUB_OUTPUT"
          echo "Found charts: ${CHARTS}"

  verify-schema:
    needs: discover-charts
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chart: ${{ fromJson(needs.discover-charts.outputs.charts) }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Changed Files
        id: changed-files
        uses: bjw-s-labs/action-changed-files@b1144fc772fca235a50902c7bb6cc431cc7d8e27 # v0.3.2
        with:
          patterns: |
            ./charts/${{ matrix.chart }}/values.yaml

      - name: Setup mise
        if: steps.changed-files.outputs.changed_files != '[]' || github.event_name == 'workflow_dispatch'
        uses: jdx/mise-action@7a111ead46986ccad89a74ad013ba2a7c08c9e67 # v2.2.1

      - name: Generate and verify helm schema
        if: steps.changed-files.outputs.changed_files != '[]' || github.event_name == 'workflow_dispatch'
        working-directory: ./charts/${{ matrix.chart }}
        run: |
          # Generate schema to a temporary file
          mise exec -- helm-schema -o /tmp/values.schema.json
          
          # Compare with the existing schema
          if ! diff -q /tmp/values.schema.json values.schema.json &>/dev/null; then
            echo "::error::The values.schema.json for chart ${{ matrix.chart }} is out of date. Please run 'helm-schema' locally and commit the changes."
            diff -u values.schema.json /tmp/values.schema.json || true
            exit 1
          fi
