---
name: Build and Push Helm Chart

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - "charts/k8s-resource/**"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Set up Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
        with:
          version: v3.15.4

      - name: Helm login to GHCR
        run: |
          echo ${{ secrets.GHCR_RW_TOKEN }} | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Package Helm chart
        working-directory: ./charts/k8s-resource
        run: helm package .

      - name: Push Helm chart to GHCR
        working-directory: ./charts/k8s-resource
        run: helm push $(ls *.tgz) oci://ghcr.io/${{ github.repository }}
