# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Helm Docs
permissions: { contents: read }

on:
  workflow_dispatch: {}
  push:
    paths:
      - "charts/**/Chart.yaml"
      - "charts/**/values.yaml"
      - "charts/**/README.md.gotmpl"

jobs:
  discover-charts:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.set-charts.outputs.charts }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Find Helm Charts
        id: set-charts
        run: |
          CHARTS=$(find charts -type f -name "Chart.yaml" -print0 | xargs -0 dirname | xargs -0 -n1 basename | jq -R -s -c 'split("\n")[:-1]')
          echo "charts=${CHARTS}" >> "$GITHUB_OUTPUT"
          echo "Found charts: ${CHARTS}"

  verify-docs:
    needs: discover-charts
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chart: ${{ fromJson(needs.discover-charts.outputs.charts) }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Changed Files
        id: changed-files
        uses: bjw-s-labs/action-changed-files@b1144fc772fca235a50902c7bb6cc431cc7d8e27 # v0.3.2
        with:
          patterns: |
            ./charts/${{ matrix.chart }}/Chart.yaml
            ./charts/${{ matrix.chart }}/values.yaml
            ./charts/${{ matrix.chart }}/README.md.gotmpl

      - name: Setup mise
        if: steps.changed-files.outputs.changed_files != '[]' || github.event_name == 'workflow_dispatch'
        uses: jdx/mise-action@7a111ead46986ccad89a74ad013ba2a7c08c9e67 # v2.2.1

      - name: Generate and verify helm docs
        if: steps.changed-files.outputs.changed_files != '[]' || github.event_name == 'workflow_dispatch'
        working-directory: ./charts/${{ matrix.chart }}
        run: |
          # Generate docs to a temporary file
          mise exec -- helm-docs -o /tmp/README.md

          # Compare with the existing README.md
          if ! diff -q /tmp/README.md README.md &>/dev/null; then
            echo "::error::The README.md for chart ${{ matrix.chart }} is out of date. Please run 'helm-docs' locally and commit the changes."
            diff -u README.md /tmp/README.md || true
            exit 1
          fi
