---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@6ed7b667628510c8fd2dedf74f2492c24652dccf # v3.8.0
    secrets: inherit
    with:
      config-file: .github/labeler.yaml