---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Meta - Labeler

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/meta-labeler.yaml@ad68966d90780c09542180ea2f598d0befc6990f
    secrets: inherit
    with:
      config-file: ".github/configs/labeler.yaml"
